name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Build app
        run: ./scripts/buildprod.sh

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build image
        run: docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/notely:${{ steps.vars.outputs.IMAGE_TAG }} .

      - name: Push image
        run: docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/notely:${{ steps.vars.outputs.IMAGE_TAG }}
     
      - name: Ping Render
        run: curl -sS -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
      
